name: Deploy Lambda REST API

on:
  push:
    branches: ["main", "dev"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      STACK_NAME: lambda-rest-api-${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::779844646698:role/ln-custom-deployment-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Build
        run: npm run build
      # If not bootstrapped for this account/region, do it once manually (see step 5)
      - name: CDK Bootstrap
        run: npx cdk bootstrap aws://779844646698/${{ env.AWS_REGION }}

      - name: Synthesize
        run: npm run cdk:synth

      - name: Deploy
        run: npx cdk deploy $STACK_NAME --context env=prod --require-approval never

      - name: Show API URL
        run: |
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
            --output text
